// 리그 → 팀 프리셋 (큐레이션, 외부 API 키 불필요).
// 선수는 pid(실선수 고유번호)로 고정한다 — 이름 부분일치는 "디아스"처럼 동명이인을 잘못 집었다.
// 라인업은 2025-26 시즌 기준 대표 선발. pid 는 넥슨 spid.json 으로 전부 대조했다.
// 해석 시 그 선수의 최신 시즌 카드를 쓴다. 못 찾으면 슬롯 비움(사용자가 채움).
// 커버리지 확장은 추후 API-Football(/players/squads) 연동으로.

export interface PresetPlayer {
  pos: string; // 포지션 라벨 (GK, CB, ST ...)
  name: string; // FC온라인 한글 표기(spid.json 그대로)
  pid?: number; // 실선수 고유번호 — 있으면 이름 대신 이것으로 찾는다
}

export interface TeamPreset {
  id: string;
  league: string;
  team: string;
  formation: string;
  players: PresetPlayer[];
}

export const PRESETS: TeamPreset[] = [
  {
    id: "arsenal",
    league: "프리미어리그",
    team: "아스날",
    formation: "433",
    players: [
      { pos: "GK", name: "다비드 라야", pid: 220901 },
      { pos: "RB", name: "위리엔 팀버", pid: 251805 },
      { pos: "CB", name: "윌리암 살리바", pid: 243715 },
      { pos: "CB", name: "가브리엘 마갈량이스", pid: 232580 },
      { pos: "LB", name: "R. 칼라피오리", pid: 257711 },
      { pos: "CM", name: "데클런 라이스", pid: 234378 },
      { pos: "CM", name: "수비멘디", pid: 248148 },
      { pos: "CM", name: "마르틴 외데고르", pid: 222665 },
      { pos: "RW", name: "부카요 사카", pid: 246669 },
      { pos: "ST", name: "빅토르 요케레스", pid: 241651 },
      { pos: "LW", name: "가브리엘 마르티넬리", pid: 251566 },
    ],
  },
  {
    id: "mancity",
    league: "프리미어리그",
    team: "맨체스터 시티",
    formation: "433",
    players: [
      { pos: "GK", name: "잔루이지 돈나룸마", pid: 230621 },
      { pos: "RB", name: "마테우스 누네스", pid: 253124 },
      { pos: "CB", name: "후벵 디아스", pid: 239818 },
      { pos: "CB", name: "그바르디올", pid: 251517 },
      { pos: "LB", name: "N. 오라일리", pid: 277427 },
      { pos: "CM", name: "로드리", pid: 231866 },
      { pos: "CM", name: "T. 레인더르스", pid: 240638 },
      { pos: "CM", name: "필 포든", pid: 237692 },
      { pos: "RW", name: "라얀 셰르키", pid: 251570 },
      { pos: "ST", name: "엘링 홀란", pid: 239085 },
      { pos: "LW", name: "제레미 도쿠", pid: 246420 },
    ],
  },
  {
    id: "liverpool",
    league: "프리미어리그",
    team: "리버풀",
    formation: "4231",
    players: [
      { pos: "GK", name: "알리송", pid: 212831 },
      { pos: "RB", name: "제레미 프림퐁", pid: 253149 },
      { pos: "CB", name: "이브라히마 코나테", pid: 237678 },
      { pos: "CB", name: "버질 반다이크", pid: 203376 },
      { pos: "LB", name: "M. 케르케즈", pid: 260908 },
      { pos: "CDM", name: "R. 흐라벤베르흐", pid: 246104 },
      { pos: "CDM", name: "A. 마칼리스테르", pid: 239837 },
      { pos: "CAM", name: "플로리안 비르츠", pid: 256630 },
      { pos: "RAM", name: "모하메드 살라", pid: 209331 },
      { pos: "LAM", name: "코디 각포", pid: 242516 },
      { pos: "ST", name: "알렉산데르 이사크", pid: 233731 },
    ],
  },
  {
    id: "tottenham",
    league: "프리미어리그",
    team: "토트넘",
    formation: "4231",
    players: [
      { pos: "GK", name: "G. 비카리오", pid: 240091 },
      { pos: "RB", name: "페드로 포로", pid: 243576 },
      { pos: "CB", name: "크리스티안 로메로", pid: 232488 },
      { pos: "CB", name: "미키 반더벤", pid: 264453 },
      { pos: "LB", name: "D. 우도기", pid: 259583 },
      { pos: "CDM", name: "팔리냐", pid: 229391 },
      { pos: "CDM", name: "로드리고 벤탕쿠르", pid: 227535 },
      { pos: "CAM", name: "차비 시몬스", pid: 245367 },
      { pos: "RAM", name: "모하메드 쿠두스", pid: 245155 },
      { pos: "LAM", name: "윌슨 오도베르", pid: 270579 },
      { pos: "ST", name: "도미닉 솔랑키", pid: 225539 },
    ],
  },
  {
    id: "manutd",
    league: "프리미어리그",
    team: "맨체스터 유나이티드",
    formation: "4231",
    players: [
      { pos: "GK", name: "S. 라먼스", pid: 254803 },
      { pos: "RB", name: "디오구 달로", pid: 234574 },
      { pos: "CB", name: "해리 매과이어", pid: 203263 },
      { pos: "CB", name: "L. 마르티네스", pid: 239301 },
      { pos: "LB", name: "루크 쇼", pid: 205988 },
      { pos: "CDM", name: "카제미루", pid: 200145 },
      { pos: "CDM", name: "코비 메이누", pid: 269136 },
      { pos: "CAM", name: "브루누 페르난데스", pid: 212198 },
      { pos: "RAM", name: "브라이언 음뵈모", pid: 243014 },
      { pos: "LAM", name: "마테우스 쿠냐", pid: 240243 },
      { pos: "ST", name: "베냐민 셰슈코", pid: 260592 },
    ],
  },
  {
    id: "chelsea",
    league: "프리미어리그",
    team: "첼시",
    formation: "4231",
    players: [
      { pos: "GK", name: "로베르트 산체스", pid: 228789 },
      { pos: "RB", name: "리스 제임스", pid: 238074 },
      { pos: "CB", name: "웨슬리 포파나", pid: 248695 },
      { pos: "CB", name: "트레보 찰로바", pid: 230918 },
      { pos: "LB", name: "마르크 쿠쿠레야", pid: 239231 },
      { pos: "CDM", name: "M. 카이세도", pid: 256079 },
      { pos: "CDM", name: "엔소 페르난데스", pid: 247090 },
      { pos: "CAM", name: "콜 파머", pid: 257534 },
      { pos: "RAM", name: "이스테방", pid: 76687 },
      { pos: "LAM", name: "페드루 네투", pid: 238616 },
      { pos: "ST", name: "주앙 페드루", pid: 252042 },
    ],
  },
  {
    id: "newcastle",
    league: "프리미어리그",
    team: "뉴캐슬",
    formation: "433",
    players: [
      { pos: "GK", name: "닉 포프", pid: 203841 },
      { pos: "RB", name: "키어런 트리피어", pid: 186345 },
      { pos: "CB", name: "파비안 셰어", pid: 210047 },
      { pos: "CB", name: "스벤 보트만", pid: 251809 },
      { pos: "LB", name: "L. 홀", pid: 266127 },
      { pos: "CM", name: "산드로 토날리", pid: 241096 },
      { pos: "CM", name: "브루누 기마랑이스", pid: 247851 },
      { pos: "CM", name: "조엘린통", pid: 223334 },
      { pos: "RW", name: "제이컵 머피", pid: 206085 },
      { pos: "ST", name: "닉 볼테마데", pid: 254022 },
      { pos: "LW", name: "앤서니 고든", pid: 242964 },
    ],
  },
  {
    id: "astonvilla",
    league: "프리미어리그",
    team: "아스톤 빌라",
    formation: "4231",
    players: [
      { pos: "GK", name: "에미 마르티네스", pid: 202811 },
      { pos: "RB", name: "매티 캐시", pid: 227174 },
      { pos: "CB", name: "에즈리 콘사", pid: 227678 },
      { pos: "CB", name: "파우 토레스", pid: 241464 },
      { pos: "LB", name: "뤼카 디뉴", pid: 200458 },
      { pos: "CDM", name: "부바카르 카마라", pid: 236987 },
      { pos: "CDM", name: "유리 틸레만스", pid: 216393 },
      { pos: "CAM", name: "모건 로저스", pid: 260247 },
      { pos: "RAM", name: "존 맥긴", pid: 210881 },
      { pos: "LAM", name: "E. 부엔디아", pid: 226162 },
      { pos: "ST", name: "올리 왓킨스", pid: 221697 },
    ],
  },
  {
    id: "realmadrid",
    league: "라리가",
    team: "레알 마드리드",
    formation: "433",
    players: [
      { pos: "GK", name: "티보 쿠르투아", pid: 192119 },
      { pos: "RB", name: "T. 알렉산더-아놀드", pid: 231281 },
      { pos: "CB", name: "에데르 밀리탕", pid: 240130 },
      { pos: "CB", name: "딘 하위선", pid: 278349 },
      { pos: "LB", name: "알바로 카레라스", pid: 268889 },
      { pos: "CM", name: "페데리코 발베르데", pid: 239053 },
      { pos: "CM", name: "A. 추아메니", pid: 241637 },
      { pos: "CM", name: "주드 벨링엄", pid: 252371 },
      { pos: "RW", name: "호드리구", pid: 243812 },
      { pos: "ST", name: "킬리안 음바페", pid: 231747 },
      { pos: "LW", name: "비니시우스", pid: 238794 },
    ],
  },
  {
    id: "barcelona",
    league: "라리가",
    team: "바르셀로나",
    formation: "4231",
    players: [
      { pos: "GK", name: "주안 가르시아", pid: 259532 },
      { pos: "RB", name: "쥘 쿤데", pid: 241486 },
      { pos: "CB", name: "파우 쿠바르시", pid: 278046 },
      { pos: "CB", name: "R. 아라우호", pid: 253163 },
      { pos: "LB", name: "발데", pid: 263578 },
      { pos: "CDM", name: "페드리", pid: 251854 },
      { pos: "CDM", name: "프렝키 더용", pid: 228702 },
      { pos: "CAM", name: "페르민 로페스", pid: 277179 },
      { pos: "RAM", name: "라민 야말", pid: 277643 },
      { pos: "LAM", name: "하피냐", pid: 233419 },
      { pos: "ST", name: "레반도프스키", pid: 188545 },
    ],
  },
  {
    id: "atletico",
    league: "라리가",
    team: "아틀레티코 마드리드",
    formation: "442",
    players: [
      { pos: "GK", name: "얀 오블라크", pid: 200389 },
      { pos: "RB", name: "마르코스 요렌테", pid: 226161 },
      { pos: "CB", name: "로뱅 르노르망", pid: 233486 },
      { pos: "CB", name: "다비드 한츠코", pid: 247103 },
      { pos: "LB", name: "M. 루제리", pid: 259584 },
      { pos: "CM", name: "코케", pid: 193747 },
      { pos: "CM", name: "파블로 바리오스", pid: 272449 },
      { pos: "RM", name: "G. 시메오네", pid: 253396 },
      { pos: "LM", name: "알렉스 바에나", pid: 257279 },
      { pos: "ST", name: "훌리안 알바레스", pid: 246191 },
      { pos: "ST", name: "앙투안 그리즈만", pid: 194765 },
    ],
  },
  {
    id: "inter",
    league: "세리에 A",
    team: "인터 밀란",
    formation: "352",
    players: [
      { pos: "GK", name: "얀 조머", pid: 177683 },
      { pos: "CB", name: "마누엘 아칸지", pid: 229237 },
      { pos: "CB", name: "F. 아체르비", pid: 199845 },
      { pos: "CB", name: "A. 바스토니", pid: 237383 },
      { pos: "RWB", name: "덴젤 둠프리스", pid: 233096 },
      { pos: "CM", name: "니콜로 바렐라", pid: 224232 },
      { pos: "CM", name: "하칸 찰하놀루", pid: 208128 },
      { pos: "CM", name: "헨릭 미키타리안", pid: 192883 },
      { pos: "LWB", name: "F. 디마르코", pid: 226268 },
      { pos: "ST", name: "라우타로", pid: 231478 },
      { pos: "ST", name: "마르쿠스 튀람", pid: 228093 },
    ],
  },
  {
    id: "acmilan",
    league: "세리에 A",
    team: "AC 밀란",
    formation: "352",
    players: [
      { pos: "GK", name: "마이크 메냥", pid: 215698 },
      { pos: "CB", name: "피카요 토모리", pid: 232756 },
      { pos: "CB", name: "마테오 가비아", pid: 240277 },
      { pos: "CB", name: "S. 파블로비치", pid: 254840 },
      { pos: "RWB", name: "A. 살레마커르스", pid: 242664 },
      { pos: "CM", name: "유수프 포파나", pid: 245630 },
      { pos: "CM", name: "루카 모드리치", pid: 177003 },
      { pos: "CM", name: "아드리앙 라비오", pid: 210008 },
      { pos: "LWB", name: "P. 에스투피냔", pid: 237942 },
      { pos: "ST", name: "하파엘 레앙", pid: 241721 },
      { pos: "ST", name: "크리스천 풀리식", pid: 227796 },
    ],
  },
  {
    id: "juventus",
    league: "세리에 A",
    team: "유벤투스",
    formation: "4231",
    players: [
      { pos: "GK", name: "M. 디 그레고리오", pid: 235840 },
      { pos: "RB", name: "P. 칼룰루", pid: 255654 },
      { pos: "CB", name: "F. 가티", pid: 266872 },
      { pos: "CB", name: "브레메르", pid: 239580 },
      { pos: "LB", name: "J. 카발", pid: 251870 },
      { pos: "CDM", name: "마누엘 로카텔리", pid: 222077 },
      { pos: "CDM", name: "K. 튀람", pid: 247246 },
      { pos: "CAM", name: "퇸 코프메이너르스", pid: 240679 },
      { pos: "RAM", name: "프란시스쿠 콘세이상", pid: 261050 },
      { pos: "LAM", name: "K. 일디즈", pid: 277954 },
      { pos: "ST", name: "두샨 블라호비치", pid: 246430 },
    ],
  },
  {
    id: "napoli",
    league: "세리에 A",
    team: "나폴리",
    formation: "433",
    players: [
      { pos: "GK", name: "S. 밀린코비치-사비치", pid: 223848 },
      { pos: "RB", name: "조반니 디로렌초", pid: 217870 },
      { pos: "CB", name: "아미르 라흐마니", pid: 244263 },
      { pos: "CB", name: "A. 부온조르노", pid: 243241 },
      { pos: "LB", name: "M. 올리베라", pid: 240716 },
      { pos: "CM", name: "S. 로보트카", pid: 216435 },
      { pos: "CM", name: "스콧 맥토미니", pid: 237238 },
      { pos: "CM", name: "케빈 더브라위너", pid: 192985 },
      { pos: "RW", name: "마테오 폴리타노", pid: 216409 },
      { pos: "ST", name: "라스무스 호일룬", pid: 259399 },
      { pos: "LW", name: "다비드 네리스", pid: 236632 },
    ],
  },
  {
    id: "bayern",
    league: "분데스리가",
    team: "바이에른 뮌헨",
    formation: "4231",
    players: [
      { pos: "GK", name: "마누엘 노이어", pid: 167495 },
      { pos: "RB", name: "콘라트 라이머", pid: 225375 },
      { pos: "CB", name: "다요 우파메카노", pid: 229558 },
      { pos: "CB", name: "김민재", pid: 237086 },
      { pos: "LB", name: "J. 스타니시치", pid: 250955 },
      { pos: "CDM", name: "요주아 키미히", pid: 212622 },
      { pos: "CDM", name: "A. 파블로비치", pid: 275298 },
      { pos: "CAM", name: "무시알라", pid: 256790 },
      { pos: "RAM", name: "마이클 올리세", pid: 247827 },
      { pos: "LAM", name: "루이스 디아스", pid: 241084 },
      { pos: "ST", name: "해리 케인", pid: 202126 },
    ],
  },
  {
    id: "dortmund",
    league: "분데스리가",
    team: "도르트문트",
    formation: "3421",
    players: [
      { pos: "GK", name: "그레고르 코벨", pid: 235073 },
      { pos: "CB", name: "니클라스 쥘레", pid: 212190 },
      { pos: "CB", name: "발데마르 안톤", pid: 229476 },
      { pos: "CB", name: "N. 슐로터베크", pid: 247819 },
      { pos: "RM", name: "J. 리에르손", pid: 229891 },
      { pos: "CM", name: "펠릭스 은메차", pid: 246863 },
      { pos: "CM", name: "마르셀 자비처", pid: 204923 },
      { pos: "LM", name: "D. 스벤손", pid: 259716 },
      { pos: "CAM", name: "율리안 브란트", pid: 212194 },
      { pos: "CAM", name: "니코 베이어", pid: 231178 },
      { pos: "ST", name: "세루 기라시", pid: 215441 },
    ],
  },
  {
    id: "psg",
    league: "리그 1",
    team: "파리 생제르맹",
    formation: "433",
    players: [
      { pos: "GK", name: "뤼카 슈발리에", pid: 251752 },
      { pos: "RB", name: "아슈라프 하키미", pid: 235212 },
      { pos: "CB", name: "마르키뉴스", pid: 207865 },
      { pos: "CB", name: "윌리안 파초", pid: 256196 },
      { pos: "LB", name: "누누 멘데스", pid: 252145 },
      { pos: "CM", name: "비티냐", pid: 255253 },
      { pos: "CM", name: "주앙 네베스", pid: 272834 },
      { pos: "CM", name: "이강인", pid: 243780 },
      { pos: "RW", name: "D. 두에", pid: 271421 },
      { pos: "ST", name: "우스만 뎀벨레", pid: 231443 },
      { pos: "LW", name: "크바라츠헬리아", pid: 247635 },
    ],
  },
  {
    id: "korea",
    league: "국가대표",
    team: "대한민국",
    formation: "4231",
    players: [
      { pos: "GK", name: "조현우", pid: 212432 },
      { pos: "RB", name: "설영우", pid: 254980 },
      { pos: "CB", name: "김민재", pid: 237086 },
      { pos: "CB", name: "조유민", pid: 244798 },
      { pos: "LB", name: "이태석", pid: 261063 },
      { pos: "CDM", name: "황인범", pid: 228010 },
      { pos: "CDM", name: "백승호", pid: 237424 },
      { pos: "CAM", name: "이재성", pid: 221671 },
      { pos: "RAM", name: "이강인", pid: 243780 },
      { pos: "LAM", name: "황희찬", pid: 226380 },
      { pos: "ST", name: "손흥민", pid: 200104 },
    ],
  },
  {
    id: "argentina",
    league: "국가대표",
    team: "아르헨티나",
    formation: "433",
    players: [
      { pos: "GK", name: "에미 마르티네스", pid: 202811 },
      { pos: "RB", name: "나우엘 몰리나", pid: 233084 },
      { pos: "CB", name: "크리스티안 로메로", pid: 232488 },
      { pos: "CB", name: "니콜라스 오타멘디", pid: 192366 },
      { pos: "LB", name: "N. 탈리아피코", pid: 211256 },
      { pos: "CM", name: "로드리고 데폴", pid: 212616 },
      { pos: "CM", name: "엔소 페르난데스", pid: 247090 },
      { pos: "CM", name: "A. 마칼리스테르", pid: 239837 },
      { pos: "RW", name: "리오넬 메시", pid: 158023 },
      { pos: "ST", name: "훌리안 알바레스", pid: 246191 },
      { pos: "LW", name: "라우타로", pid: 231478 },
    ],
  },
];

export function getPreset(id: string): TeamPreset | undefined {
  return PRESETS.find((p) => p.id === id);
}

/** 리그별로 묶은 팀 목록 (선택 UI용) */
export function presetsByLeague(): { league: string; teams: TeamPreset[] }[] {
  const map = new Map<string, TeamPreset[]>();
  for (const p of PRESETS) {
    const arr = map.get(p.league) ?? [];
    arr.push(p);
    map.set(p.league, arr);
  }
  return [...map.entries()].map(([league, teams]) => ({ league, teams }));
}
